apiVersion: apps/v1
kind: Deployment
metadata:
  name: wac-lab-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /wac-lab-openapi
            - name: BASE_URL
              value: /wac-lab-openapi-ui