apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: magum/wac-lab-ufe
    newName: magum/wac-lab-ufe # {"$imagepolicy":  "wac-hospital:wac-lab-ufe:name"}
    newTag: master.20240312.1044 # {"$imagepolicy": "wac-hospital:wac-lab-ufe:tag"}
  - name: milung/ufe-controller
    newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
    newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
  - name: magum/wac-lab-webapi
    newName: magum/wac-lab-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
    newTag: master # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
