apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml # namespace je tiež objektom pre tento klaster
  - ../../../infrastructure/ufe-controller # kustomization pre ufe-controller

patches:
  - path: patches/ufe-controller.service.yaml # úprava služby ufe-controller
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: "HTTP_CSP_HEADER"
          value: "default-src 'self' 'unsafe-inline' https://fonts.googleapis.com/ https://fonts.gstatic.com/; font-src 'self' https://fonts.googleapis.com/ https://fonts.gstatic.com/; script-src 'nonce-{NONCE_VALUE}'; connect-src 'self' 192.168.49.2:30331 192.168.49.2:30081"
    target:
      group: apps
      version: v1
      kind: Deployment
      name: ufe-controller

components:
  - ../../../components/version-developers
